Build v0.1.2

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -21,23 +21,23 @@ jobs:
       - name: Check if Tag Exists
         id: check_tag
         run: |
-          version=${{ steps.get_version.outputs.version }}
-          if git rev-parse "v$version" >/dev/null 2>&1; then
-            echo "Tag v$version already exists."
+          version="v${{ steps.get_version.outputs.version }}"
+          if git rev-parse "$version" >/dev/null 2>&1; then
+            echo "Tag $version already exists."
             echo "::set-output name=tag_exists::true"
           else
-            echo "Tag v$version does not exist."
+            echo "Tag $version does not exist."
             echo "::set-output name=tag_exists::false"
           fi
 
       - name: Create Tag
         if: steps.check_tag.outputs.tag_exists == 'false'
         run: |
-          version=${{ steps.get_version.outputs.version }}
+          version="v${{ steps.get_version.outputs.version }}"
           git config user.name "github-actions"
           git config user.email "github-actions@github.com"
-          git tag -a "v$version" -m "Release version $version"
-          git push origin "v$version"
+          git tag -a "$version" -m "Release version $version"
+          git push origin "$version"
 
   build:
     needs: check-version-and-tag
@@ -129,9 +129,9 @@ jobs:
       - name: Verify Created Tag
         run: |
           version=$(jq -r '.version' package.json)
-          echo "Verifying tag v$version"
-          if ! git tag -l | grep -q "v$version"; then
-            echo "Error: Tag v$version not found locally."
+          echo "Verifying tag $version"
+          if ! git tag -l | grep -q "$version"; then
+            echo "Error: Tag $version not found locally."
             exit 1
           fi
 
@@ -164,7 +164,7 @@ jobs:
       - name: Create Release
         uses: softprops/action-gh-release@v1
         with:
-          tag_name: ${{ steps.get_version.outputs.version }}
+          tag_name: "v${{ steps.get_version.outputs.version }}"
           files: |
             src-tauri/target/release/bundle/dmg/*.dmg
             src-tauri/target/release/bundle/msi/*.msi
